name: Pronouns
version: '${project.version}'
main: io.gmijo.Pronouns
api-version: '1.19'
commands:
  prounounce:
    description: Set your pronouns
    usage: /prounounce add <pronoun>
    permission: pronouns.add  # Set a custom permission node here, if desired